name: "Deploy Recipes Book Backend"
on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ../recipe-book-backend;
            rm -f .env;
            git pull;
            git fetch;
            git checkout origin/develop -- .env;
            sed -i "/PORT_DB/d" .env;
            sed -i "/DB_USER/d" .env;
            sed -i "/DB_PASSWORD/d" .env;
            sed -i "/DB_HOST/d" .env;
            echo "PORT_DB=5432" >> .env;
            echo "DB_USER=${{ secrets.DB_USERNAME }}" >> .env;
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env;
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env;
            export NVM_DIR=~/.nvm;
            source ~/.nvm/nvm.sh;
            
