name: "Deploy Recipes Book Backend"
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      - name: Set NVM_DIR
        run: export NVM_DIR="$HOME/.nvm"
      - name: Use Node.js version with NVM
        run: nvm install node
      - name: Set Node.js version with NVM
        run: nvm use node
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ../recipe-book-backend;
            git pull;
            npm -v
            npm run build;
